version: '3'

services: 
  python-service:
    build: ./
    volumes:
      - ./:/House-Price-Prediction
    

  nginx:
    build: ./nginx
    ports:
      - 3000:80
    depends_on:
  
      - python-service
    command: nginx -g 'daemon off;'
    
    

