version: '3'

services: 
  python-service:
    build: ./
    volumes:
      - ./:/House-Price-Prediction
    ports:
      - 3000:4000
    

#   nginx:
#     build: ./nginx
#     ports:
#       - 3000:80
#     depends_on:
  
#       - python-service
#     command: nginx -g 'daemon off;'
    
    

